name: Setup-Vulkan

inputs:
  version:
    description: VulkanSDK version
    required: true
    type: string
  file:
    description: File to download
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Download VulkanCI
      uses: robinraju/release-downloader@v1.10
      with:
        repository: 'NcStudios/VulkanCI'
        tag: 'v${{ inputs.version }}'
        filename: '${{ matrix.file }}'
        out-file-path: 'VulkanSDK'
        extract: true

    - name: Setup Environment Variables
      shell: bash
      run: |
        INSTALL_PATH="${{ github.workspace }}/VulkanSDK/${{ inputs.version }}"
        echo "VULKAN_SDK=$INSTALL_PATH" >> "$GITHUB_ENV"
        echo "VULKAN_SDK_VERSION=${{ inputs.version }}" >> "$GITHUB_ENV"
        echo "SWIFTSHADER_INSTALL_PATH=$INSTALL_PATH/Swiftshader" >> "$GITHUB_ENV"
        echo "$INSTALL_PATH/bin" >> "$GITHUB_PATH"
        echo "$INSTALL_PATH/lib" >> "$GITHUB_PATH"
