name: Setup-Vulkan

inputs:
  version:
    description: Vulkan SDK Version
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout Vulkan-Headers
      uses: actions/checkout@v3
      with:
        repository: 'https://github.com/KhronosGroup/Vulkan-Headers.git'
        ref: 'sdk-${{ inputs.version }}'
        path: 'Vulkan-Headers'

    - name: Build Vulkan-Headers
      shell: bash
      run: |
        cmake -S Vulkan-Headers -B Vulkan-Headers/build
        cmake --install Vulkan-Headers/build --prefix VulkanSDK/${{ inputs.version }}

    - name: Checkout Vulkan-Loader
      uses: actions/checkout@v3
      with:
        repository: 'https://github.com/KhronosGroup/Vulkan-Loader.git'
        ref: 'sdk-${{ inputs.version }}'
        path: 'Vulkan-Loader'

    - name: Build Vulkan-Loader
      shell: bash
      run: |
        cmake -S Vulkan-Loader -B Vulkan-Loader/build -DVULKAN_HEADERS_INSTALL_DIR="VulkanSDK/${{ inputs.version }}"
        cmake --install Vulkan-Loader/build --config Release
        cmake --install Vulkan-Loader/build --prefix VulkanSDK/${{ inputs.version }}

    - name: Setup Environment Variables
      shell: bash
      run: |
        echo "VULKAN_SDK=VulkanSDK/${{ inputs.version }}" >> "$GITHUB_ENV"
        echo "VULKAN_SDK_VERSION=${{ inputs.version }}" >> "$GITHUB_ENV"
        echo "VulkanSDK/${{ inputs.version }}/bin" >> "$GITHUB_PATH"

    # - name: Build Vulkan-Headers
    #   shell: bash
    #   run: |
    #       set -e

    #       version=1.3.261.1
    #       gitTag=sdk-$version

    #       sandbox="$PWD/local_vulkan_sdk"
    #       installPath="$sandbox/VulkanSDK/$version"

    #       mkdir "$sandbox"
    #       cd "$sandbox"

    #       git clone --depth 1 --branch $gitTag https://github.com/KhronosGroup/Vulkan-Headers.git
    #       cd Vulkan-Headers
    #       cmake -S ./ -B build
    #       cmake --install build --prefix "$installPath"
    #       cd ..

    #       git clone --depth 1 --branch $gitTag https://github.com/KhronosGroup/Vulkan-Loader.git
    #       cd Vulkan-Loader
    #       cmake -S ./ -B build -DVULKAN_HEADERS_INSTALL_DIR="$installPath"
    #       cmake --build build --config Release
    #       cmake --install build --prefix "$installPath"
    #       cd ..

    #       cd ..

    #       # echo "VULKAN_SDK=$installPath" >> "$GITHUB_ENV"
    #       # echo "VULKAN_SDK_VERSION=$version" >> "$GITHUB_ENV"
    #       # echo "$installPath/bin" >> "$GITHUB_PATH"

