D:\VulkanSDK\1.2.162.1\Bin\glslc.exe %~dp0\..\project\shaders\Environment.vert -o %~dp0\..\project\shaders\Compiled\EnvironmentVertex.spv
D:\VulkanSDK\1.2.162.1\Bin\glslc.exe %~dp0\..\project\shaders\Environment.frag -o %~dp0\..\project\shaders\Compiled\EnvironmentFragment.spv
D:\VulkanSDK\1.2.162.1\Bin\glslc.exe %~dp0\..\project\shaders\Particle.vert -o %~dp0\..\project\shaders\Compiled\ParticleVertex.spv
D:\VulkanSDK\1.2.162.1\Bin\glslc.exe %~dp0\..\project\shaders\Particle.frag -o %~dp0\..\project\shaders\Compiled\ParticleFragment.spv
D:\VulkanSDK\1.2.162.1\Bin\glslc.exe %~dp0\..\project\shaders\Phong.vert -o %~dp0\..\project\shaders\Compiled\PhongVertex.spv
D:\VulkanSDK\1.2.162.1\Bin\glslc.exe %~dp0\..\project\shaders\Phong.frag -o %~dp0\..\project\shaders\Compiled\PhongFragment.spv
D:\VulkanSDK\1.2.162.1\Bin\glslc.exe %~dp0\..\project\shaders\ShadowMapping.vert -o %~dp0\..\project\shaders\Compiled\ShadowMappingVertex.spv
D:\VulkanSDK\1.2.162.1\Bin\glslc.exe %~dp0\..\project\shaders\ShadowMapping.frag -o %~dp0\..\project\shaders\Compiled\ShadowMappingFragment.spv
D:\VulkanSDK\1.2.162.1\Bin\glslc.exe %~dp0\..\project\shaders\Wireframe.vert -o %~dp0\..\project\shaders\Compiled\WireframeVertex.spv
D:\VulkanSDK\1.2.162.1\Bin\glslc.exe %~dp0\..\project\shaders\Wireframe.frag -o %~dp0\..\project\shaders\Compiled\WireframeFragment.spv