name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 5'
  pull_request:
    branches: [ vnext, release ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.config'
      - '**/*.ini'
      - '**/*.fbx'
      - '**/*.nca'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'

jobs:
  Build:
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04]
        variant: [Dev, Prod]
        include:
          - os: windows-2022
            generator: "Visual Studio 17 2022"
            shortName: Windows
          - os: ubuntu-22.04
            shortName: Linux
            generator: "Unix Makefiles"
            cmakeEnv: "CXX=/usr/bin/g++-13"
          - variant: Dev
            cmakeArgs: "-DNC_PROFILING_ENABLED=ON"
          - variant: Prod
            cmakeArgs: "-DNC_PROD_BUILD=ON"

    name: ${{ matrix.shortName }}-${{ matrix.variant }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Setup MSVC
        if: ${{ matrix.shortName == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install X11
        if: ${{ matrix.shortName == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install xorg-dev

      - name: Setup Vulkan SDK
        uses: ./.github/workflows/setup-vulkan
        with:
          version: 1.3.261.1

      - name: Configure
        run: ${{ matrix.cmakeEnv }} cmake -G "${{ matrix.generator }}" -S . -B build ${{ matrix.cmakeArgs }} -DCMAKE_INSTALL_PREFIX=install -DNC_BUILD_TESTS=ON

      - name: Build and Install
        run: cmake --build build --target install --config Release

      - name: Run Tests
        working-directory: ${{github.workspace}}/build/test
        run: ctest -V --output-on-failure --output-junit TestResults.xml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.shortName }}-${{ matrix.variant }}-TestResults
          path: build/test/TestResults.xml

  Publish-Test-Results:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      checks: write
      pull-requests: write
    if: always()

    steps:
    - name: Download Results
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Publish Results
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: 'artifacts/**/*.xml'
