name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ vnext ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.config'
      - '**/*.ini'
      - '**/*.fbx'
      - '**/*.nca'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'

jobs:
  Build:
    runs-on: windows-2022

    steps:
    - name: Build NcEngine
      uses: NcStudios/NcEngine/.github/workflows/build-template.yml@main
      with:
        presetName: NcEngine-MSVC-Release-WithEditor
        sourceDir: ${{github.workspace}}/engine
    
    - name: MSVC Code Analysis
      uses: microsoft/msvc-code-analysis-action@04825f6d9e00f87422d6bf04e1a38b1f3ed60d99
      # Provide a unique ID to access the sarif output path
      id: run-analysis
      with:
        cmakeBuildDirectory: '${{ github.workspace }}/build/NcEngine-MSVC-Release'

  Test:
    runs-on: windows-2022
    
    steps:
    - name: Build Tests
      uses: NcStudios/NcEngine/.github/workflows/build-template.yml@main
      with:
        presetName: Tests-MSVC
        sourceDir: ${{github.workspace}}/test
        
    - name: Run Tests
      working-directory: ${{github.workspace}}/build/Tests-MSVC
      run: ctest -V
  
