name: Windows

on:
  pull_request:
    branches: [ vnext ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.config'
      - '**/*.ini'
      - '**/*.fbx'
      - '**/*.nca'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
 
    - name: Setup Vulkan Sdk
      uses: humbletim/setup-vulkan-sdk@v1.0.3
 
    - name: Configure Tests
      run: cmake -S ${{github.workspace}}/test -B ${{github.workspace}}/build/Tests-MSVC --preset Tests-MSVC

    - name: Build Tests
      run: cmake --build ${{github.workspace}}/build/Tests-MSVC

    - name: Run Tests
      working-directory: ${{github.workspace}}/build/Tests-MSVC
      run: ctest -V
    
    - name: Configure NcEngine Lib
      run: cmake -S ${{github.workspace}}/nc -B ${{github.workspace}}/build/NcEngine-MSVC-Release --preset NcEngine-MSVC-Release
    
    - name: Build NcEngine Lib
      run: cmake --build ${{github.workspace}}/build/NcEngine-MSVC-Release
